# Generated by Django 3.2.16 on 2022-11-23 16:47

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('country', models.CharField(default=None, max_length=255)),
                ('state', models.CharField(default=None, max_length=255)),
                ('city', models.CharField(default=None, max_length=255)),
                ('address', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
