# Generated by Django 3.2.16 on 2022-11-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0002_city_country_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='s_name',
        ),
    ]
