# Generated by Django 3.2.16 on 2022-11-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0005_alter_userdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='lang',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lat',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
